### ISSUE TITLE
Joplin 1.4+ compatibility issues

### ISSUE THREAD

**Issue by codelesscody** [cerealkella/rest-uploader#6]
rest-uploader broke for me in Windows 10 after upgrading from Joplin 1.3.18 to 1.4.19. Tested all Joplin 1.4 releases (1.4.19, 1.4.18, 1.4.16) - same error. Rolled back to 1.3.18 and rest-uploader is working fine again. Possible issues with [Joplin's new plugin API changes](https://discourse.joplinapp.org/t/plugin-support-in-joplin-1-4/12786)?

I'm running the following relevant programs (all working with 1.3.18, only change was upgrading Joplin to 1.4.x):

Windows 10 Enterprise 20H2 (Build 19042.662)
Python 3.9.0
Joplin 1.4.19
Poppler 0.89.0
Tesseract 5.0.0-alpha.20200328

Stack Trace:

```
PS C:\Program Files\Python39\Scripts> .\rest_uploader.exe C:\users\userprofile\.joplin_scan_inbox\
Launching Application rest_uploader.cli.main
Endpoint: http://127.0.0.1:41184
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\rest_uploader.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\program files\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python39\lib\site-packages\rest_uploader\cli.py", line 126, in main
    notebook_id = set_notebook_id(destination.strip())
  File "c:\program files\python39\lib\site-packages\rest_uploader\rest_uploader.py", line 153, in set_notebook_id
    if folder.get("title") == NOTEBOOK_NAME:
AttributeError: 'str' object has no attribute 'get'
```

**Comment by mzguy** [comment]
Me too!

**Comment by codelesscody** [comment]
> 
> 
> Me too!

@kellerjustin wasn't able to replicate the problem, so I'm planning on digging in and doing further testing, so any tips you can provide on replicating the issue would be great.

From Discord:
> kellerjustin12/05/2020
> In very minimal testing on a new system I was able to run rest_uploader against Joplin 1.4... Is there a chance when upgrading > that the web clipper service either got disabled or switched ports?

**Comment by mzguy** [comment]
I'm running:
Windows 7 64-bit
Joplin 1.4.19
Python 3.8.6 64-bit
Poppler 0.68.0
Tesseract 5.0.0-alpha.20200328

My stack trace looks identical to yours. From that, it appears there's as issue with a data element, but I'm not sure why. Here are the relevant lines:

```
File "C:\Users\Maciek\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_uploader\rest_uploader.py", line 153, in set_notebook_id
    if folder.get("title") == NOTEBOOK_NAME:
AttributeError: 'str' object has no attribute 'get'
```

Perhaps it has to do with the arguments being passed?

I'm launching with the following (from a batch file, with path names replaced with <path> for simplicity and privacy:
`
python <Path>\rest_uploader.exe -l eng -d "2 File" -t no -o <Path2> <Path3> 1>stdout.txt 2>stderr.txt`

**Comment by codelesscody** [comment]
@mzguy issue resolved -- @kellerjustin just pushed an updated rest-uploader version 1.13 to fix this. Update to the latest and it should be good to go. I had to stop my running rest-uploader scheduled task, then upgraded with "pip install rest_uploader --upgrade" and it's processing files against Joplin 1.4.19 again. Cheers!

**Comment by mzguy** [comment]
Thanks for the heads up!
